.\" -*- nroff -*-
.\" Copyright 2013, 2014 by Christophe Duverger.  All Rights Reserved.
.\" This file may be copied under the terms of the GNU Public License.
.\" 
.TH UNRM.FATX 8 "January  2014"
.SH NAME
unrm.fatx \- tries to recover deleted files on an Xbox fatx file system
.SH SYNOPSIS
.B unrm.fatx
[
.B \-aflntvy
]
[
.B \-\-nodate
)
[
.B \-\-nolost
]
[
.B \-\-offset
.I offset
]
[
.B \-\-size
.I size
]
[
.B \-p | \-\-partition sc|gc|cp|x1|x2
]
[
.B \-i | \-\-input
]
.I device
.SH DESCRIPTION
.B unrm.fatx
can recover deleted files in a fatx file system.
.PP
.I device
is the device file where the file system is stored (e.g. /dev/hdXX).
.PP
If the
.B \-\-local
option is used, the program recovers files in the current directory outside the fatx file system.
Otherwise, it recovers files and directories in the fatx file system.
.SH OPTIONS
.TP
.B \-a, \-\-auto
Give the default answer to all questions. Allows 
.B unrm.fatx
to be used non-interactively.
.TP
.B \-f, \-\-nofat
Disable recovery of lost chains in file allocation table.
.TP
.B \-h, \-\-help
Print summary of options and exit.
.TP
.B \-i, \-\-input device
Set the
.I device
file where the file system is.
.TP
.B \-l, \-\-local
Recovered files are written in the current directory instead of in the fatx file system.
This option implies the
.B \-t
option: the file system is opened read only.
.TP
.B \-n, \-\-none
Assume an answer of ``no'' to all questions. Allows 
.B unrm.fatx
to be used non-interactively.
.TP
.B \-p, \-\-partition sc|gc|cp|x1|x2
Choose the partition to be checked, depending on the device. By default, xbox 2 partition is selected.
.br
.B sc
\	to select system cache partition
.br
.B gc
\	to select game cache partition
.br
.B cp
\	to select content cache partition
.br
.B x1
\	to select xbox 1 partition
.br
.B x2
\	to select xbox 2 partition
.TP
.B \-t, \-\-test
Open the file system read-only.
.TP
.B \-v, \-\-verbose
Verbose mode.
.TP
.B \-y, \-\-all
Assume an answer of ``yes'' to all questions. Allows 
.B unrm.fatx
to be used non-interactively.
.TP
.B \-\-nodate
Disable dates precedence of deleted files in the recovery algorithm.
.TP
.B \-\-nolost
Disable preservation of lost chains in the recovery algorithm.
.TP
.B \-\-offset offset
Force
.I offset
of the partition to be checked in the device. This option disables the identification of partition mapping of the device.
.TP
.B \-\-size size
Force
.I size
of the partition to be checked in the device. This option disables the identification of partition mapping of the device.
.TP
.B --version
Print version information and exit.
.SH EXIT CODE
The exit code returned by
.B unrm.fatx
is the sum of the following conditions:
.br
0\	no error
.br
8\	operational error
.br
16\	usage or syntax error
.SH REPORTING BUGS
If you manage to find a file system which causes 
.B unrm.fatx
to crash, please report it to the author.
.PP
Please include as much information as possible in your bug report.
Ideally, include a complete transcript of the
.B unrm.fatx
run, so I can see exactly what error messages are displayed.  If you
have a writeable file system where the transcript can be stored, the 
.BR script (1)
program is a handy way to save the output of
.B unrm.fatx
to a file.
.PP
Always include the full version string which 
.B unrm.fatx
displays when it is run with
.B \-\-version
option, so I know which version you are running.
.SH AUTHOR
This version of
.B unrm.fatx
is written by Christophe DUVERGER <baxter@about.org>.
.SH SEE ALSO
.BR mkfs.fatx (8),
.BR label.fatx (8),
.BR fsck.fatx (8),
.BR fusefatx (8)
